export const Types = {
    FETCHED_PLUGINS_SUCCESSFULLY: "FETCHED_PLUGINS_SUCCESSFULLY",
    FETCHED_TABS_SUCCESSFULLY: "FETCHED_TABS_SUCCESSFULLY",
    FILTERED_FETCHED_PLUGINS_SUCCESSFULLY:"FILTERED_FETCHED_PLUGINS_SUCCESSFULLY",
    SERVER_ERROR:"SERVER_ERROR",
    PLUGINS_UPDATED_SUCCESSFULLY:"PLUGINS_UPDATED_SUCCESSFULLY"
  };
  